### ISSUE TITLE
can't load textures

### ISSUE THREAD

**Issue by tomxu-wellington** [pokepetter/ursina#188]
Traceback (most recent call last):
  File "D:\Users\tomx2\Documents\coding\learning\minecraft\mc.py", line 5, in <module>
    grass_texture = load_texture('assets/grass_block.png')
  File "C:\Users\tomx2\AppData\Local\Programs\Python\Python37\lib\site-packages\ursina\texture_importer.py", line 40, in load_texture
    t =  Texture(filename.resolve())
  File "C:\Users\tomx2\AppData\Local\Programs\Python\Python37\lib\site-packages\ursina\texture.py", line 23, in __init__
    self._texture = loader.loadTexture(Filename.fromOsSpecific(str(value)))
NameError: name 'loader' is not defined

**Comment by pokepetter** [comment]
Instantiate Ursina() before loading textures.
