### ISSUE TITLE
Ursina crashes when F5 is pressed

### ISSUE THREAD

**Issue by ELginas** [pokepetter/ursina#189]
I'm working on improved version of FirstPersonController for my game, but pressing F5 in game crashes Ursina.

```python
Traceback (most recent call last):
  File "...\UrsinaCraft\main.py", line 37, in <module>
    app.run()
  File "...\Python\Python39\lib\site-packages\ursina\main.py", line 231, in run
    super().run()
  File "...\Python\Python39\lib\site-packages\direct\showbase\ShowBase.py", line 3325, in run
    self.taskMgr.run()
  File "...\Python\Python39\lib\site-packages\direct\task\Task.py", line 546, in run
    self.step()
  File "...\Python\Python39\lib\site-packages\direct\task\Task.py", line 500, in step
    self.mgr.poll()
  File "...\Python\Python39\lib\site-packages\ursina\main.py", line 130, in _update
    entity.update()
  File "...\UrsinaCraft\first_person_controller.py", line 21, in update
    self.update_movement()
  File "...\UrsinaCraft\first_person_controller.py", line 41, in update_movement
    self.move(self.position + self.velocity * time.dt)
  File "...\UrsinaCraft\first_person_controller.py", line 60, in move
    hit_info = boxcast(world_position, (0, 0, 0), distance=0, thickness=(.1, .1), ignore=(self,))
  File "...\Python\Python39\lib\site-packages\ursina\raycaster.py", line 101, in boxcast
    Raycaster._boxcast_box.enabled = True
  File "...\Python\Python39\lib\site-packages\ursina\entity.py", line 151, in __setattr__
    self.unstash()
AssertionError: !is_singleton() && !is_empty() at line 5229 of panda/src/pgraph/nodePath.cxx
```
The main cause of this issue is that boxcast uses something which is freed when F5 is pressed. I tried surrounding boxcast with try/except. It didn't crash, but everytime boxcast was called after F5, it showed me this error:
`Assertion failed: !is_singleton() && !is_empty() at line 5229 of panda/src/pgraph/nodePath.cxx`

This is my code:
```python
from ursina import *
from fps_camera import FPSCamera

class FirstPersonController(Entity):
    def __init__(self, **kwargs):
        super().__init__(origin_y=-.5, color=color.red)
        self.camera = FPSCamera(parent=self, y=2)

        self.speed = 5
        self.jump_velocity = 10
        self.fall_acceleration = 0.1

        self.grounded = False
        self.velocity = Vec3(0, 0, 0)

        for key, value in kwargs.items():
            setattr(self, key, value)

    def update(self):
        self.update_camera()
        self.update_movement()

    def update_camera(self):
        self.rotation_y += mouse.velocity[0] * self.camera.mouse_sensitivity[1]

        self.camera.rotation_x -= mouse.velocity[1] * self.camera.mouse_sensitivity[0]
        self.camera.rotation_x = clamp(self.camera.rotation_x, -90, 90)
    
    def update_movement(self):
        direction = Vec3(
            self.forward * (held_keys['w'] - held_keys['s'])
            + self.right * (held_keys['d'] - held_keys['a'])
        ).normalized()

        self.velocity.x = direction.x * self.speed
        self.velocity.z = direction.z * self.speed
        if not self.grounded:
            self.velocity.y -= self.fall_acceleration
        print(self.velocity)

        self.move(self.position + self.velocity * time.dt)
        self.update_gravity()
    
    def update_gravity(self):  
        ray = raycast(self.world_position, self.down, 0.1, ignore=(self,))

        if ray.hit:
            self.grounded = True
            self.velocity.y = 0
        else:
            self.grounded = False

    
    def move(self, position):
        if self.position == position:
            return
        
        world_position = self.world_position - (self.position - position)
        # Internal ursina bug. When you press F5, it crashes
        try:
            hit_info = boxcast(world_position, (0, 0, 0), distance=0, thickness=(.1, .1), ignore=(self,))
            if not hit_info.hit:
                self.position = position
        except:
            pass
    
    def input(self, key):
        if key == 'space':
            self.jump()

    def jump(self):
        if not self.grounded:
            return

        self.velocity.y += self.jump_velocity
```

**Comment by pokepetter** [comment]
Seems like an internal Entity used by the raycaster wasn't marked as eternal, and thus got destroyed when it shouldn't have been. Should be fixed now :)
