### ISSUE TITLE
TypeError: C++ object is not yet constructed, or already destructed. failed to load heightmap: loddefjord_height_map

### ISSUE THREAD

**Issue by SyntaxTerror484** [pokepetter/ursina#193]
Hi I tried to create a terrain mesh and i got the error in the title so i copy pasted the code from the sample and still got the same error. here is the full error
Traceback (most recent call last):
  File "C:\Users\username\PycharmProjects\oop\oop.py", line 5, in <module>
    e = Entity(model=Terrain('loddefjord_height_map', skip=8), texture='loddefjord_color', scale=100, scale_y=50)
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\site-packages\ursina\entity.py", line 102, in __init__
    setattr(self, key, value)
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\site-packages\ursina\entity.py", line 193, in __setattr__
    if self.model:
TypeError: C++ object is not yet constructed, or already destructed.
failed to load heightmap: loddefjord_height_map

Process finished with exit code 1

my code is the same as the sample terrain_mesh.py
can anyone help me?
thanks

**Comment by pokepetter** [comment]
You don't have the heightmap in your folder. It's located in samples/textures if you want it
