### ISSUE TITLE
Ursina can't open window on Linux

### ISSUE THREAD

**Issue by benj5378** [pokepetter/ursina#211]
Recreate the problem:
1. Boot into Ubuntu Ubuntu 20.04.2 LTS
2. Run `pip3 install ursina`
3. Go through the guide on the website
    1) Create an empty .py file called 'ursina_game.py'
    2) Copy this text into your new file:

```
from ursina import *
app = Ursina()
player = Entity(model='cube', color=color.orange, scale_y=2)
def update():   # update gets automatically called.
    player.x += held_keys['d'] * .1
    player.x -= held_keys['a'] * .1

app.run()
```

iii. Type this in the terminal to start the game. I recommend setting a hotkey for this in your text editor: python ursina_game.py

4. Get the following error:
```
          ursina version: 3.5.0
          package_folder: /home/benj5378/.local/lib/python3.8/site-packages/ursina
          asset_folder: .
          blender_paths:
          {}
          OS: posix
          screen resolution: (1920, 1080)
          Known pipe types:
            glxGraphicsPipe
          (4 aux display modules not yet loaded.)
          :display:x11display(error): BadValue (integer parameter out of range for operation)
          :display:glxdisplay(error): Could not find a usable pixel format.
          :display:glxdisplay(error): No GLX context: cannot open window.
          :display:gsg:glgsg(warning): Unable to query GL_VENDOR
          :display:gsg:glgsg(warning): Unable to query GL_RENDERER
          :display:gsg:glgsg(warning): Unable to query GL_VERSION
          :display:gsg:glgsg(error): Unable to detect OpenGL version
          :display:gsg:glgsg(warning): Unable to query GL_VENDOR
          :display:gsg:glgsg(warning): Unable to query GL_RENDERER
          :display:gsg:glgsg(warning): Unable to query GL_VERSION
          :display:gsg:glgsg(error): Unable to detect OpenGL version
          :display(warning): Unable to load libtinydisplay.so: No error.
          :display(warning): Unable to load libpandadx8.so: No error.
          :display(warning): Unable to load libpandadx9.so: No error.
          :ShowBase(warning): Unable to open 'onscreen' window.
          Traceback (most recent call last):
            File "main.py", line 3, in <module>
              app = Ursina()
            File "/home/benj5378/.local/lib/python3.8/site-packages/ursina/main.py", line 19, in __init__
              super().__init__()
            File "/home/benj5378/.local/lib/python3.8/site-packages/direct/showbase/ShowBase.py", line 339, in __init__
              self.openDefaultWindow(startDirect = False, props=props)
            File "/home/benj5378/.local/lib/python3.8/site-packages/direct/showbase/ShowBase.py", line 1021, in openDefaultWindow
              self.openMainWindow(*args, **kw)
            File "/home/benj5378/.local/lib/python3.8/site-packages/direct/showbase/ShowBase.py", line 1056, in openMainWindow
              self.openWindow(*args, **kw)
            File "/home/benj5378/.local/lib/python3.8/site-packages/direct/showbase/ShowBase.py", line 801, in openWindow
              raise Exception('Could not open window.')
          Exception: Could not open window.
```
5. Go to Windows and run the same code without any errors.

**Comment by pokepetter** [comment]
I tried it on Pop OS and it worked there, so I'm not sure what it can be

**Comment by t0a5ted** [comment]
Followed the steps on my Ubuntu 20.04 LTS install, and the window opened perfectly fine, displaying the orange cube. ( This is a fresh Ubuntu install ).

I think this is an issue on your side, not ursina's.
