### ISSUE TITLE
problem in ursina

### ISSUE THREAD

**Issue by pragithr123** [pokepetter/ursina#235]
my code is 
from ursina import *

app = Ursina()

app.run()

output is 
ursina version: 3.6.0
package_folder: E:\python__\lib\site-packages\ursina
asset_folder: .
blender_paths:
{'default': WindowsPath('E:/blender.exe')}
screen resolution: (1366, 768)
Known pipe types:
  wglGraphicsPipe
(3 aux display modules not yet loaded.)
:display(error): The application requested harware acceleration, but your OpenGL
:display(error): driver, GDI Generic, only supports software rendering.
:display(error): You need to install a hardware-accelerated OpenGL driver, or,
:display(error): if you actually *want* to use a software renderer, then
:display(error): alter the hardware/software configuration in your Config.prc file.
:display(warning): Unable to load libtinydisplay.so: Path not found
:display(warning): Unable to load libpandadx8.so: Path not found
:display(warning): Unable to load libpandadx9.so: Module not found
:ShowBase(warning): Unable to open 'onscreen' window.
Traceback (most recent call last):
  File "E:\rpggame.py\maingame.py", line 4, in <module>
    app = Ursina()
  File "E:\python__\lib\site-packages\ursina\main.py", line 28, in __init__
    super().__init__()
  File "E:\python__\lib\site-packages\direct\showbase\ShowBase.py", line 339, in __init__
    self.openDefaultWindow(startDirect = False, props=props)
  File "E:\python__\lib\site-packages\direct\showbase\ShowBase.py", line 1021, in openDefaultWindow
    self.openMainWindow(*args, **kw)
  File "E:\python__\lib\site-packages\direct\showbase\ShowBase.py", line 1056, in openMainWindow
    self.openWindow(*args, **kw)
  File "E:\python__\lib\site-packages\direct\showbase\ShowBase.py", line 801, in openWindow
    raise Exception('Could not open window.')
Exception: Could not open window.

**Comment by pokepetter** [comment]
Read the error message: 
 You need to install a hardware-accelerated OpenGL driver
