### ISSUE TITLE
AttributeError: module 'gltf' has no attribute 'patch_loader'

### ISSUE THREAD

**Issue by burnt-melon** [pokepetter/ursina#237]
I am on Windows 10 home and whenever I try running my script, it shows,

```
ursina version: 3.6.0
package_folder: C:\Users\****\AppData\Local\Programs\Python\Python39\lib\site-packages\ursina
asset_folder: .
blender_paths:
{}
screen resolution: (1920, 1080)
Known pipe types:
  wglGraphicsPipe
(3 aux display modules not yet loaded.)
Traceback (most recent call last):
  File "C:\Users\****\Documents\Programming\python\ursina\myapp.py", line 5, in <module>
    app = Ursina()
  File "C:\Users\****\AppData\Local\Programs\Python\Python39\lib\site-packages\ursina\main.py", line 30, in __init__
    gltf.patch_loader(self.loader)
AttributeError: module 'gltf' has no attribute 'patch_loader'

````
It used to work normally but after I failed to compile my script, ursina stops working to even run it.
I have tried fulling deleting and installing both ursina and gltf again but same thing happens.

**Comment by pokepetter** [comment]
Use the github version of ursina, as it's more up to date.

**Comment by pokepetter** [comment]
What problem?

**Comment by qisia** [comment]
Maybe a lower version could help, try gltf==0.13?
