### ISSUE TITLE
NameError: name 'render' is not defined

### ISSUE THREAD

**Issue by maverick-dev-55** [pokepetter/ursina#239]
# Full Error
``` python
Traceback (most recent call last):
  File "c:\Users\RedRa\Documents\vscode\untitled-game\main.py", line 23, in 
<module>
    quitbutton = Button(text='Quit', color=color.azure)
  File "C:\Users\RedRa\AppData\Roaming\Python\Python39\site-packages\ursina\prefabs\button.py", line 26, in __init__
    self.model = Quad(aspect=self.scale[0] / self.scale[1])
  File "C:\Users\RedRa\AppData\Roaming\Python\Python39\site-packages\ursina\models\procedural\quad.py", line 11, in Quad
    return QuadMesh(radius, segments, aspect, scale, mode, thickness)       
  File "C:\Users\RedRa\AppData\Roaming\Python\Python39\site-packages\ursina\models\procedural\quad.py", line 42, in __init__
    new_verts.append(QuadMesh.point_placer.world_position)
  File "C:\Users\RedRa\AppData\Roaming\Python\Python39\site-packages\ursina\entity.py", line 410, in world_position
    return Vec3(self.get_position(render))
NameError: name 'render' is not defined
```
How do i fix this error?
i am following the minecraft tutorial and wanted a menu but it says a variable isnt defined inside ursina code

**Comment by maverick-dev-55** [comment]
Ok, i checked https://github.com/pokepetter/ursina/blob/31cb718a1aac635ebc996e87f1ff3b688f793633/ursina/entity.py#L410 and i dont see any reference of a variable called 'render', was it meant to be a parameter?

**Comment by maverick-dev-55** [comment]
A snippet of my code:
``` python
quitbutton = Button(text='Quit', color=color.azure)
quitbutton.on_click = quit
wp = WindowPanel(
    title='Menu',
    content=(
        quitbutton,
        Slider(),
        Slider(),
        ),
        popup=True,
        enabled=False
    )
def input(key):
    if key == 'escape':
        wp.enabled = True
```

**Comment by pokepetter** [comment]
You need to create an instance of Ursina first.

**Comment by maverick-dev-55** [comment]
i already did

**Comment by pokepetter** [comment]
no
