### ISSUE TITLE
No blend Installation was found Windows

### ISSUE THREAD

**Issue by starosin** [pokepetter/ursina#273]
Hi! I can't load blend files in ursina, I always gets this error

Traceback (most recent call last):
  File "C:\Users\LENEVO\Downloads\Mincraft.py", line 36, in <module>
    K = Entity(model = "untitled")
  File "C:\Users\LENEVO\AppData\Roaming\Python\Python39\site-packages\ursina\entity.py", line 102, in __init__
    setattr(self, key, value)
  File "C:\Users\LENEVO\AppData\Roaming\Python\Python39\site-packages\ursina\entity.py", line 194, in __setattr__
    m = load_model(value, application.asset_folder)
  File "C:\Users\LENEVO\AppData\Roaming\Python\Python39\site-packages\ursina\mesh_importer.py", line 62, in load_model
    if compress_models(path=path, name=name):
  File "C:\Users\LENEVO\AppData\Roaming\Python\Python39\site-packages\ursina\mesh_importer.py", line 192, in compress_models
    blender = get_blender(blend_file)
  File "C:\Users\LENEVO\AppData\Roaming\Python\Python39\site-packages\ursina\mesh_importer.py", line 163, in get_blender
    raise Exception('error: trying to load .blend file, but no blender installation was found.')
Exception: error: trying to load .blend file, but no blender installation was found.

this is the code:

from ursina import *
app = Ursina()
K = Entity(model = "sword", scale = (2,2,2))
Sky()
app.run()

please respond

**Comment by starosin** [comment]
I am using WINDOWS

**Comment by pokepetter** [comment]
Do you have Blender installed?

**Comment by starosin** [comment]
Yes have

**Comment by pokepetter** [comment]
Have you rebooted after blender got installed? Where did you install it, the default location or somewhere else?

**Comment by starosin** [comment]
Yes, Idid and It's in the default location

**Comment by pokepetter** [comment]
Then I don't know. 
You can try setting `application.blender_paths['default'] = Path('C:\...')` manually.

**Comment by buddha314** [comment]
OKAY! So I fixed this. I had installed Blender via Steam.  Don't ask me why. But then I removed it from Steam and reinstalled using `choco`, that appears to have fixed several issues.
