### ISSUE TITLE
Cant build the game by using a venv

### ISSUE THREAD

**Issue by swalsberger** [pokepetter/ursina#276]
Hi pokepetter,

i have a problem to build the game when i using a python venv, because the ursina.build script is searching in the wrong directory for the python executable.

The default search directory is the "Lib" directory, but in the venv the python executable lies in the "Script" directory.

`
copying python
copying python Lib files
Traceback (most recent call last):
  File "C:\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\development\my stuff\ursina\ursina\build.py", line 131, in <module>
    [copy(str(f), str(python_lib_dest / f.name)) for f in Path(python_folder / 'Lib').iterdir() if f.is_file()]
  File "c:\development\my stuff\ursina\ursina\build.py", line 131, in <listcomp>
    [copy(str(f), str(python_lib_dest / f.name)) for f in Path(python_folder / 'Lib').iterdir() if f.is_file()]
  File "C:\Python37\lib\pathlib.py", line 1074, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [WinError 3] No such file or directory: 'C:\\...\\venv\\Scripts\\Lib'
make: *** [compile] Error 1
`

**Comment by swalsberger** [comment]
it is working w/o using a venv.

The game is isolated after you built it, but i dont like it to polute my global python installation. I always use an venv on my python projects.

i modified my build.py file for a more generic solution
