### ISSUE TITLE
widnow problem

### ISSUE THREAD

**Issue by smjt2000** [pokepetter/ursina#387]
Hi.
I'm using ArtixLinux with OpenRC and KDE.
I installed Ursina a few days age and I have a problem with window. I can't resize and move the window.
if I try to move the window, it will disappear but the app is still running.
if I use `window.fullscreen=True` I got this error:
```
Traceback (most recent call last):
  File "/home/smjt2000/.local/lib/python3.10/site-packages/direct/showbase/EventManager.py", line 49, in eventLoopTask
    self.doEvents()
  File "/home/smjt2000/.local/lib/python3.10/site-packages/direct/showbase/EventManager.py", line 43, in doEvents
    processFunc(dequeueFunc())
  File "/home/smjt2000/.local/lib/python3.10/site-packages/direct/showbase/EventManager.py", line 99, in processEvent
    messenger.send(eventName, paramList)
  File "/home/smjt2000/.local/lib/python3.10/site-packages/direct/showbase/Messenger.py", line 337, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "/home/smjt2000/.local/lib/python3.10/site-packages/direct/showbase/Messenger.py", line 422, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "/home/smjt2000/.local/lib/python3.10/site-packages/direct/showbase/ShowBase.py", line 3002, in windowEvent
    self.adjustWindowAspectRatio(self.getAspectRatio())
  File "/home/smjt2000/.local/lib/python3.10/site-packages/direct/showbase/ShowBase.py", line 3091, in adjustWindowAspectRatio
    messenger.send("aspectRatioChanged")
  File "/home/smjt2000/.local/lib/python3.10/site-packages/direct/showbase/Messenger.py", line 337, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "/home/smjt2000/.local/lib/python3.10/site-packages/direct/showbase/Messenger.py", line 422, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "/home/smjt2000/.local/lib/python3.10/site-packages/ursina/window.py", line 180, in update_aspect_ratio
    for e in [e for e in scene.entities if e.parent == camera.ui] + self.editor_ui.children:
AttributeError: 'NoneType' object has no attribute 'children'
:task(error): Exception occurred in PythonTask eventManager
Traceback (most recent call last):
  File "/home/smjt2000/Programming/ursina-samples/s2.py", line 13, in <module>
    app.run()
  File "/home/smjt2000/.local/lib/python3.10/site-packages/ursina/main.py", line 239, in run
    super().run()
  File "/home/smjt2000/.local/lib/python3.10/site-packages/direct/showbase/ShowBase.py", line 3328, in run
    self.taskMgr.run()
  File "/home/smjt2000/.local/lib/python3.10/site-packages/direct/task/Task.py", line 553, in run
    self.step()
  File "/home/smjt2000/.local/lib/python3.10/site-packages/direct/task/Task.py", line 504, in step
    self.mgr.poll()
  File "/home/smjt2000/.local/lib/python3.10/site-packages/direct/showbase/EventManager.py", line 49, in eventLoopTask
    self.doEvents()
  File "/home/smjt2000/.local/lib/python3.10/site-packages/direct/showbase/EventManager.py", line 43, in doEvents
    processFunc(dequeueFunc())
  File "/home/smjt2000/.local/lib/python3.10/site-packages/direct/showbase/EventManager.py", line 99, in processEvent
    messenger.send(eventName, paramList)
  File "/home/smjt2000/.local/lib/python3.10/site-packages/direct/showbase/Messenger.py", line 337, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "/home/smjt2000/.local/lib/python3.10/site-packages/direct/showbase/Messenger.py", line 422, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "/home/smjt2000/.local/lib/python3.10/site-packages/direct/showbase/ShowBase.py", line 3002, in windowEvent
    self.adjustWindowAspectRatio(self.getAspectRatio())
  File "/home/smjt2000/.local/lib/python3.10/site-packages/direct/showbase/ShowBase.py", line 3091, in adjustWindowAspectRatio
    messenger.send("aspectRatioChanged")
  File "/home/smjt2000/.local/lib/python3.10/site-packages/direct/showbase/Messenger.py", line 337, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "/home/smjt2000/.local/lib/python3.10/site-packages/direct/showbase/Messenger.py", line 422, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "/home/smjt2000/.local/lib/python3.10/site-packages/ursina/window.py", line 180, in update_aspect_ratio
    for e in [e for e in scene.entities if e.parent == camera.ui] + self.editor_ui.children:
AttributeError: 'NoneType' object has no attribute 'children'

```

**Comment by y2bad** [comment]
you need to set `window.borderless` to false

**Comment by smjt2000** [comment]
> you need to set `window.borderless` to false

Thanks
