### ISSUE TITLE
AttributeError: 'Entity' object has no attribute '_texture_offset'

### ISSUE THREAD

**Issue by SamMatzko** [pokepetter/ursina#409]
I cloned the repository to run all the examples, but when I ran `bullet_hell.py` after changing to the `samples/` directory, I get this error:

```
Traceback (most recent call last):
  File "bullet_hell.py", line 69, in <module>
    app.run()
  File "/home/user/.local/lib/python3.8/site-packages/ursina/main.py", line 239, in run
    super().run()
  File "/home/user/.local/lib/python3.8/site-packages/direct/showbase/ShowBase.py", line 3328, in run
    self.taskMgr.run()
  File "/home/user/.local/lib/python3.8/site-packages/direct/task/Task.py", line 553, in run
    self.step()
  File "/home/user/.local/lib/python3.8/site-packages/direct/task/Task.py", line 504, in step
    self.mgr.poll()
  File "/home/user/.local/lib/python3.8/site-packages/ursina/main.py", line 130, in _update
    __main__.update()
  File "bullet_hell.py", line 26, in update
    bg.texture_offset += Vec2(0, time.dt)
  File "/home/user/.local/lib/python3.8/site-packages/ursina/entity.py", line 783, in texture_offset
    return self._texture_offset
AttributeError: 'Entity' object has no attribute '_texture_offset'
```

Does anyone know the fix for this? I'm running Ubuntu 20.04.4 (GNOME).

**Comment by pokepetter** [comment]
Update ursina.

**Comment by SamMatzko** [comment]
@pokepetter I've got version [4.1.1](https://pypi.org/project/ursina/4.1.1/) installed, but this code was run using a clone of this repo. As far as I can tell by looking at pypi.org, GitHub, and pip, I've got the latest of everything. Is there something I'm missing?
