### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by RinkaGI** [pokepetter/ursina#454]
I make a simple app in Ursina Engine and I want to export to Windows, i used `python3 -m ursina.build` btw, I use Windows but I have got Python3 from Microsoft Store, so I use python3 and not py 

This is the code:
```py
from ursina import *
from ursina.shaders import lit_with_shadows_shader
from ursina.prefabs.first_person_controller import FirstPersonController
import sys

app = Ursina()

# Algunas configuraciones
window.size = (1280, 890)
Entity.default_shader = lit_with_shadows_shader
random.seed(0)
Sky()

# El jugador
player = FirstPersonController()

# Se me olvidó que necesitaba un suelo
class Suelo(Entity):
    def __init__(self, position):
        super().__init__(
            parent = scene,
            position = position,
            model = 'cube',
            texture = 'grass',
            origin_y = .5,
            collider = 'box' # Se me olvidó que tenía que ponerle el collider
        )

for z in range(16):
    for x in range(16):
        Suelo(position=(x, -1, z))

# Por ultimo el sol para que se vea mas bonito :D
sun = DirectionalLight()
sun.look_at(Vec3(1, -1, -1))

# Entrada de teclado
def input(key):
    if key == 'escape':
        quit()
        sys.exit(0)
        
app.run()
```

And so I use that command and i receive this things on terminal
```
package_folder: C:\Users\rinka\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ursina    
asset_folder: .
building project: C:\Users\rinka\Desktop\Alvagame\justagame
copying python
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\rinka\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ursina\build.py", line 134, in <module>
    [copy(str(f), str(python_dest / f.name)) for f in python_folder.iterdir() if f.is_file()]
  File "C:\Users\rinka\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ursina\build.py", line 134, in <listcomp>
    [copy(str(f), str(python_dest / f.name)) for f in python_folder.iterdir() if f.is_file()]
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\rinka\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\idle.exe'
```

What can I do?

**Comment by pokepetter** [comment]
Do you have idle open or something? I'm not sure if that's it.
