### ISSUE TITLE
it gives me random error

### ISSUE THREAD

**Issue by x17db19** [pokepetter/ursina#476]
![legit](https://user-images.githubusercontent.com/106544970/197560633-0021285d-f484-4d8f-9edd-4b7563c0342b.png)
Traceback (most recent call last):
  File "C:/Users/block/Desktop/gane.py", line 1, in <module>
    from ursina import *
  File "C:\Users\block\AppData\Local\Programs\Python\Python310\lib\site-packages\ursina\__init__.py", line 27, in <module>
    from ursina.raycaster import raycast, boxcast
  File "C:\Users\block\AppData\Local\Programs\Python\Python310\lib\site-packages\ursina\raycaster.py", line 14, in <module>
    class Raycaster(Entity):
  File "C:\Users\block\AppData\Local\Programs\Python\Python310\lib\site-packages\ursina\raycaster.py", line 16, in Raycaster
    _boxcast_box = Entity(model='cube', origin_z=-.5, collider='box', color=color.white33, enabled=False, eternal=True)
  File "C:\Users\block\AppData\Local\Programs\Python\Python310\lib\site-packages\ursina\entity.py", line 109, in __init__
    setattr(self, key, kwargs[key])
  File "C:\Users\block\AppData\Local\Programs\Python\Python310\lib\site-packages\ursina\entity.py", line 205, in __setattr__
    m = load_model(value, application.asset_folder)
  File "C:\Users\block\AppData\Local\Programs\Python\Python310\lib\site-packages\ursina\mesh_importer.py", line 42, in load_model
    for filename in path.glob(f'**/{name}{filetype}'):
  File "C:\Users\block\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1034, in glob
    for p in selector.select_from(self):
  File "C:\Users\block\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 492, in _select_from
    for starting_point in self._iterate_directories(parent_path, is_dir, scandir):
  File "C:\Users\block\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 482, in _iterate_directories
    for p in self._iterate_directories(path, is_dir, scandir):
  File "C:\Users\block\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 482, in _iterate_directories
    for p in self._iterate_directories(path, is_dir, scandir):
  File "C:\Users\block\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 482, in _iterate_directories
    for p in self._iterate_directories(path, is_dir, scandir):
  [Previous line repeated 13 more times]
  File "C:\Users\block\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 471, in _iterate_directories
    with scandir(parent_path) as scandir_it:
FileNotFoundError: [WinError 3] Not finding the specified path: 'C:\\Users\\block\\Desktop\\web_client\\node_modules\\prismarine-viewer\\AppData\\Local\\Packages\\MicrosoftTeams_8wekyb3d8bbwe\\LocalCache\\Microsoft\\MSTeams\\EBWebView\\Default\\Service Worker\\CacheStorage\\a957449e0c17def967fb86220c8cab1d9f0a68fc\\a584ef95-b93f-40dd-8b74-7f4946b445db'

**Comment by y2bad** [comment]
its not random it clearly says: `FileNotFoundError: [WinError 3] Not finding the specified path: 'C:\Users\block\Desktop\web_client\node_modules\prismarine-viewer\AppData\Local\Packages\MicrosoftTeams_8wekyb3d8bbwe\LocalCache\Microsoft\MSTeams\EBWebView\Default\Service Worker\CacheStorage\a957449e0c17def967fb86220c8cab1d9f0a68fc\a584ef95-b93f-40dd-8b74-7f4946b445db'`

**Comment by pokepetter** [comment]
By having the script directly on you desktop, everything on the desktop is now part of your project and ursina will search for models and textures there. You should put your script in a separate folder. Ideally one folder per project.

**Comment by x17db19** [comment]
ok
