### ISSUE TITLE
Building with ursina.build.

### ISSUE THREAD

**Issue by imbomania** [pokepetter/ursina#534]
Win11, Python 3.11.3, without venv
When i trying to start my builded app from .bat file it logs this:

Traceback (most recent call last):
  File "C:\Vis\main.py", line 2, in <module>
    import app
  File "C:\Vis\app.py", line 2, in <module>
    from ursina import *
  File "C:\Vis\build\python\Lib\site-packages\ursina\__init__.py", line 2, in <module>
    from pathlib import Path
  File "C:\Vis\build\python\Lib\pathlib.py", line 1, in <module>
    import fnmatch
  File "C:\Vis\build\python\Lib\fnmatch.py", line 14, in <module>
    import re
ModuleNotFoundError: No module named 're'

Since this is a Python built-in module, i can't include this by --include_modules when building the app, right?
 all code is [here](https://github.com/imbomania/Vis/tree/master)

**Comment by pokepetter** [comment]
Is this with the most recent ursina from github?

**Comment by imbomania** [comment]
5.2.0 pip installed.

**Comment by pokepetter** [comment]
Try the most recent ursina from github.

**Comment by imbomania** [comment]
Now i got this:

package_folder: C:\Vis\build_Windows\python\Lib\site-packages\ursina
asset_folder: src
Traceback (most recent call last):
  File "C:\Vis\main.py", line 2, in <module>
    import app
  File "C:\Vis\app.py", line 2, in <module>
    from ursina import *
  File "C:\Vis\build_Windows\python\Lib\site-packages\ursina\__init__.py", line 9, in <module>
    from ursina.window import instance as window
  File "C:\Vis\build_Windows\python\Lib\site-packages\ursina\window.py", line 10, in <module>
    from screeninfo import get_monitors
ModuleNotFoundError: No module named 'screeninfo'

**Comment by imbomania** [comment]
Doesn't work with --include_modules, and if i manually put screeninfo in build, raises:
[log.txt](https://github.com/pokepetter/ursina/files/11267634/log.txt)

**Comment by imbomania** [comment]
Ok, it seems build works for now.
But i'm still can't run my app, because of screeninfo raising "screeninfo.common.ScreenInfoError: No enumerators available".
If there's no advices, i suppose issue can be closed.
