### ISSUE TITLE
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

### ISSUE THREAD

**Issue by fredi-python** [pokepetter/ursina#573]
```
Traceback (most recent call last):
  File "/home/fredi/PycharmProjects/Games/main.py", line 11, in <module>
    ground = Entity(model=Terrain('heightmap_1', skip=8), scale=(40,5,20), texture='heightmap_1')
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fredi/PycharmProjects/Games/venv/lib/python3.11/site-packages/ursina/models/procedural/terrain.py", line 33, in __init__
    self.height_values = texture_to_height_values(heightmap, skip)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fredi/PycharmProjects/Games/venv/lib/python3.11/site-packages/ursina/models/procedural/terrain.py", line 20, in texture_to_height_values
    img = img.resize([width, depth], Image.ANTIALIAS)
                                     ^^^^^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
```

**Comment by pokepetter** [comment]
Fixed.
