### ISSUE TITLE
TypeError: update() takes 0 positional arguments but 1 was given

### ISSUE THREAD

**Issue by GH0STH4CKER** [pokepetter/ursina#575]
Traceback (most recent call last):
  File "C:\Users\Dimuth De Zoysa\AppData\Local\Programs\Python\Python310\lib\site-packages\ursina\main.py", line 147, in _update
    __main__.update(self)
TypeError: update() takes 0 positional arguments but 1 was given
:task(error): Exception occurred in PythonTask update
Traceback (most recent call last):
  File "c:\Users\Dimuth De Zoysa\Desktop\Python_projects\fpsdemo.py", line 111, in <module>
    app.run()
  File "C:\Users\Dimuth De Zoysa\AppData\Local\Programs\Python\Python310\lib\site-packages\ursina\main.py", line 284, in run
    super().run()
  File "C:\Users\Dimuth De Zoysa\AppData\Local\Programs\Python\Python310\lib\site-packages\direct\showbase\ShowBase.py", line 3330, in run
    self.taskMgr.run()
  File "C:\Users\Dimuth De Zoysa\AppData\Local\Programs\Python\Python310\lib\site-packages\direct\task\Task.py", line 553, in run
    self.step()
  File "C:\Users\Dimuth De Zoysa\AppData\Local\Programs\Python\Python310\lib\site-packages\direct\task\Task.py", line 504, in step
    self.mgr.poll()
  File "C:\Users\Dimuth De Zoysa\AppData\Local\Programs\Python\Python310\lib\site-packages\ursina\main.py", line 147, in _update
    __main__.update(self)
TypeError: update() takes 0 positional arguments but 1 was given

**Comment by GH0STH4CKER** [comment]
https://github.com/pokepetter/ursina/pull/576
#576 opened 1 minute ago by [GH0STH4CKER](https://github.com/pokepetter/ursina/issues?q=is%3Apr+is%3Aopen+author%3AGH0STH4CKER)
