### ISSUE TITLE
diggin_game.py     @after(.101) NameError: name 'after' is not defined. Did you mean: 'aiter'?

### ISSUE THREAD

**Issue by GH0STH4CKER** [pokepetter/ursina#583]
Traceback (most recent call last):
  File "C:\Users\Dimuth De Zoysa\AppData\Local\Programs\Python\Python310\lib\site-packages\direct\showbase\EventManager.py", line 49, in eventLoopTask
    self.doEvents()
  File "C:\Users\Dimuth De Zoysa\AppData\Local\Programs\Python\Python310\lib\site-packages\direct\showbase\EventManager.py", line 43, in doEvents
    processFunc(dequeueFunc())
  File "C:\Users\Dimuth De Zoysa\AppData\Local\Programs\Python\Python310\lib\site-packages\direct\showbase\EventManager.py", line 99, in processEvent
    messenger.send(eventName, paramList)
  File "C:\Users\Dimuth De Zoysa\AppData\Local\Programs\Python\Python310\lib\site-packages\direct\showbase\Messenger.py", line 337, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "C:\Users\Dimuth De Zoysa\AppData\Local\Programs\Python\Python310\lib\site-packages\direct\showbase\Messenger.py", line 422, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "C:\Users\Dimuth De Zoysa\AppData\Local\Programs\Python\Python310\lib\site-packages\ursina\main.py", line 231, in input
    if entity.input(key):
  File "c:\Users\Dimuth De Zoysa\Desktop\Python_projects\digger.py", line 47, in input
    self.fall()
  File "c:\Users\Dimuth De Zoysa\Desktop\Python_projects\digger.py", line 72, in fall
    @after(.101)
NameError: name 'after' is not defined. Did you mean: 'aiter'?
:task(error): Exception occurred in PythonTask eventManager
Traceback (most recent call last):
  File "c:\Users\Dimuth De Zoysa\Desktop\Python_projects\digger.py", line 101, in <module>
    app.run()
  File "C:\Users\Dimuth De Zoysa\AppData\Local\Programs\Python\Python310\lib\site-packages\ursina\main.py", line 284, in run
    super().run()
  File "C:\Users\Dimuth De Zoysa\AppData\Local\Programs\Python\Python310\lib\site-packages\direct\showbase\ShowBase.py", line 3330, in run
    self.taskMgr.run()
  File "C:\Users\Dimuth De Zoysa\AppData\Local\Programs\Python\Python310\lib\site-packages\direct\task\Task.py", line 553, in run
    self.step()
  File "C:\Users\Dimuth De Zoysa\AppData\Local\Programs\Python\Python310\lib\site-packages\direct\task\Task.py", line 504, in step
    self.mgr.poll()
  File "C:\Users\Dimuth De Zoysa\AppData\Local\Programs\Python\Python310\lib\site-packages\direct\showbase\EventManager.py", line 49, in eventLoopTask
    self.doEvents()
  File "C:\Users\Dimuth De Zoysa\AppData\Local\Programs\Python\Python310\lib\site-packages\direct\showbase\EventManager.py", line 43, in doEvents
    processFunc(dequeueFunc())
  File "C:\Users\Dimuth De Zoysa\AppData\Local\Programs\Python\Python310\lib\site-packages\direct\showbase\EventManager.py", line 99, in processEvent
    messenger.send(eventName, paramList)
  File "C:\Users\Dimuth De Zoysa\AppData\Local\Programs\Python\Python310\lib\site-packages\direct\showbase\Messenger.py", line 337, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "C:\Users\Dimuth De Zoysa\AppData\Local\Programs\Python\Python310\lib\site-packages\direct\showbase\Messenger.py", line 422, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "C:\Users\Dimuth De Zoysa\AppData\Local\Programs\Python\Python310\lib\site-packages\ursina\main.py", line 231, in input
    if entity.input(key):
  File "c:\Users\Dimuth De Zoysa\Desktop\Python_projects\digger.py", line 47, in input
    self.fall()
  File "c:\Users\Dimuth De Zoysa\Desktop\Python_projects\digger.py", line 72, in fall
    @after(.101)
NameError: name 'after' is not defined. Did you mean: 'aiter'?

**Comment by pokepetter** [comment]
You're using an old ursina version. Please use v6.0.0 or newer.
