### ISSUE TITLE
Error and Warnings when running on macOS 12.6.8

### ISSUE THREAD

**Issue by walchko** [pokepetter/ursina#594]
I get the following errors when running a simple program in python 3.11 in a virtual environment:

```
:prc(warning): Invalid integer value for ConfigVariable win-size: 1152.0
:prc(warning): Invalid integer value for ConfigVariable win-size: 720.0
Known pipe types:
  CocoaGraphicsPipe
(3 aux display modules not yet loaded.)
2023-10-07 15:06:54.575 Python[67546:3396453] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/8m/htkq_jv500b_1yqyk33q6tzc0000gn/T/org.python.python.savedState
set window position: Vec2(144, 90)
:pnmimage:png(warning): iCCP: known incorrect sRGB profile
package_folder: /Users/kevin/venvs/ursina/lib/python3.11/site-packages/ursina
asset_folder: .
:display:gsg:glgsg(error): An error occurred while compiling GLSL vertex shader created-shader:
ERROR: created-shader:1: '' :  version '150' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL fragment shader created-shader:
ERROR: created-shader:2: '' :  version '150' is not supported
:display:cocoadisplay(warning): Could not find filename textures/ursina.ico
:display:cocoadisplay(error): Could not load image from file textures/ursina.ico
```

Is there something I can do to fix this?

Also, I have to click outside the game window and then click the game window to get the red button in the top right to show up with the fps. When the window closes, I get this:

```
Traceback (most recent call last):
  File "/Users/kevin/venvs/ursina/lib/python3.11/site-packages/ursina/mouse.py", line 149, in input
    self.hovered_entity.on_click()
  File "/Users/kevin/venvs/ursina/lib/python3.11/site-packages/ursina/application.py", line 65, in quit
    sys.exit()
SystemExit
```

**Comment by walchko** [comment]
I can't find what is calling this 

```
:display:cocoadisplay(warning): Could not find filename textures/ursina.ico
:display:cocoadisplay(error): Could not load image from file textures/ursina.ico
```

If I do:

```python
print('package_folder:', application.package_folder)
print('asset_folder:', application.asset_folder)
```

I get:

```
package_folder: /Users/kevin/venvs/ursina/lib/python3.11/site-packages/ursina
asset_folder: .
```

`asset_folder` isn't being set up correctly.

**Comment by pokepetter** [comment]
The error about "Could not load image" is just a missing icon and shouldn't matter or stop the program from working. 
Asset folder seems correct.

The real error here is:
```
:display:gsg:glgsg(error): An error occurred while compiling GLSL vertex shader created-shader:
ERROR: created-shader:1: '' :  version '150' is not supported
```
Does you graphics card and driver not support this GLSL version? If so, you can simply not use these shaders.

Unfortunately Apple decided to make their own shading language and only support that instead of the open standard. I think in the future there might be automatic cross compilation of shaders.

The bug with having to "click outside the game window and then click the game window", I don't know anything about. What's the code and steps to reproduce? Does it only happen in borderless or not?

**Comment by walchko** [comment]
thanks!
