### ISSUE TITLE
AttributeError when loading textures -> load_texture() 

### ISSUE THREAD

**Issue by OfficialAhmed** [pokepetter/ursina#613]
Loading a texture 
```python
load_texture("texture_name.jpg")
```
Raises the following exception

`AttributeError: 'Texture' object has no attribute '_cached_image'`

Here's the Traceback

```CMD
Traceback (most recent call last):
  File "Game Development\main.py", line 4, in <module>
    clothes_texture = load_texture("face.jpg")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Game Development\venv\Lib\site-packages\ursina\texture_importer.py", line 43, in load_texture
    t = Texture(filename.resolve(), filtering=filtering)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Game Development\venv\Lib\site-packages\ursina\texture.py", line 22, in __init__
    self._texture = loader.loadTexture(Filename.fromOsSpecific(str(value)))
                    ^^^^^^
NameError: name 'loader' is not defined

Exception ignored in: <function Texture.__del__ at 0x000001EA82DD36A0>
Traceback (most recent call last):
  File "Game Development\venv\Lib\site-packages\ursina\texture.py", line 188, in __del__
    del self._cached_image
        ^^^^^^^^^^^^^^^^^^
AttributeError: 'Texture' object has no attribute '_cached_image'

```

**Comment by pokepetter** [comment]
You have to instantiate Ursina() before loading textures.
Also, the correct way to load textures is simply texture='texture_name' wen creating the entity. See https://www.ursinaengine.org/entity_basics.html#Texture
