### ISSUE TITLE
Conversation is broken

### ISSUE THREAD

**Issue by ValleyDragon888** [pokepetter/ursina#627]
`Conversation()` is currently broken. Upon running both the example in `conversation.py`, and code from the website (which look to be the same), I get the error:
```
Traceback (most recent call last):
  File "C:\Users\SimonFlint\Desktop\ursina-template-with-level-editor\main.py", line 39, in <module>
    conversation.start_conversation(convo)
  File "C:\Users\SimonFlint\Desktop\ursina-template-with-level-editor\venv\Lib\site-packages\ursina\prefabs\conversation.py", line 148, in start_conversation
    self.ask(self.conversation_nodes[0])
  File "C:\Users\SimonFlint\Desktop\ursina-template-with-level-editor\venv\Lib\site-packages\ursina\prefabs\conversation.py", line 59, in ask
    self.question_appear_sequence = self.question.text_entity.appear(delay=.1)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Text.appear() got an unexpected keyword argument 'delay'

```

**Comment by ValleyDragon888** [comment]
Upon changing line 59 of `conversation.py` to this:
`        self.question_appear_sequence = self.question.text_entity.appear()`
the problem is fixed!

**Comment by pokepetter** [comment]
fixed
