### ISSUE TITLE
ValueError when running `particle_system.py`

### ISSUE THREAD

**Issue by rayannott** [pokepetter/ursina#642]
I get an operand mismatch ValueError when running the `particle_system.py` script:

```python
python particle_system.py
:prc(warning): Invalid integer value for ConfigVariable win-size: 864.0
:prc(warning): Invalid integer value for ConfigVariable win-size: 1536.0
Known pipe types:
  wglGraphicsPipe
(3 aux display modules not yet loaded.)
set window position: Vec2(192, 108)
:prc(warning): changing default value for ConfigVariable paste-emit-keystrokes from '1' to '0'.
:pnmimage:png(warning): iCCP: known incorrect sRGB profile
package_folder: C:\Users\Airat\Desktop\other-coding\ursina-testin\ursina\samples\venv\Lib\site-packages\ursina
asset_folder: .
os: Windows
development mode: True
application successfully started
info: changed aspect ratio: 1.778 -> 1.778
:display:windisplay(warning): Could not find icon filename textures/ursina.ico
Traceback (most recent call last):
  File "C:\Users\Airat\Desktop\other-coding\ursina-testin\ursina\samples\venv\Lib\site-packages\direct\showbase\EventManager.py", line 49, in eventLoopTask
    self.doEvents()
  File "C:\Users\Airat\Desktop\other-coding\ursina-testin\ursina\samples\venv\Lib\site-packages\direct\showbase\EventManager.py", line 43, in doEvents
    processFunc(dequeueFunc())
  File "C:\Users\Airat\Desktop\other-coding\ursina-testin\ursina\samples\venv\Lib\site-packages\direct\showbase\EventManager.py", line 99, in processEvent
    messenger.send(eventName, paramList)
  File "C:\Users\Airat\Desktop\other-coding\ursina-testin\ursina\samples\venv\Lib\site-packages\direct\showbase\Messenger.py", line 337, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "C:\Users\Airat\Desktop\other-coding\ursina-testin\ursina\samples\venv\Lib\site-packages\direct\showbase\Messenger.py", line 422, in __dispatch
    result = method (*(extraArgs + sentArgs))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Airat\Desktop\other-coding\ursina-testin\ursina\samples\venv\Lib\site-packages\ursina\main.py", line 241, in input
    __main__.input(key)
  File "C:\Users\Airat\Desktop\other-coding\ursina-testin\ursina\samples\particle_system.py", line 40, in input
    p = ParticleSystem(position=Vec3(random.random(),random.random(),random.random())*2, color=color.random_color(), rotation_y=random.random()*360)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Airat\Desktop\other-coding\ursina-testin\ursina\samples\particle_system.py", line 17, in __init__
    super().__init__(model=Mesh(vertices=points, mode='point', static=False, render_points_in_3d=True, thickness=.1), t=0, duration=1, **kwargs)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Airat\Desktop\other-coding\ursina-testin\ursina\samples\venv\Lib\site-packages\ursina\mesh.py", line 75, in __init__
    if self.vertices != []:
       ^^^^^^^^^^^^^^^^^^^
ValueError: operands could not be broadcast together with shapes (1000,3) (0,)
:task(error): Exception occurred in PythonTask eventManager
Traceback (most recent call last):
  File "C:\Users\Airat\Desktop\other-coding\ursina-testin\ursina\samples\particle_system.py", line 46, in <module>
    app.run()
  File "C:\Users\Airat\Desktop\other-coding\ursina-testin\ursina\samples\venv\Lib\site-packages\ursina\main.py", line 306, in run
    super().run()
  File "C:\Users\Airat\Desktop\other-coding\ursina-testin\ursina\samples\venv\Lib\site-packages\direct\showbase\ShowBase.py", line 3330, in run
    self.taskMgr.run()
  File "C:\Users\Airat\Desktop\other-coding\ursina-testin\ursina\samples\venv\Lib\site-packages\direct\task\Task.py", line 553, in run
    self.step()
  File "C:\Users\Airat\Desktop\other-coding\ursina-testin\ursina\samples\venv\Lib\site-packages\direct\task\Task.py", line 504, in step
    self.mgr.poll()
  File "C:\Users\Airat\Desktop\other-coding\ursina-testin\ursina\samples\venv\Lib\site-packages\direct\showbase\EventManager.py", line 49, in eventLoopTask
    self.doEvents()
  File "C:\Users\Airat\Desktop\other-coding\ursina-testin\ursina\samples\venv\Lib\site-packages\direct\showbase\EventManager.py", line 43, in doEvents
    processFunc(dequeueFunc())
  File "C:\Users\Airat\Desktop\other-coding\ursina-testin\ursina\samples\venv\Lib\site-packages\direct\showbase\EventManager.py", line 99, in processEvent
    messenger.send(eventName, paramList)
  File "C:\Users\Airat\Desktop\other-coding\ursina-testin\ursina\samples\venv\Lib\site-packages\direct\showbase\Messenger.py", line 337, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "C:\Users\Airat\Desktop\other-coding\ursina-testin\ursina\samples\venv\Lib\site-packages\direct\showbase\Messenger.py", line 422, in __dispatch
    result = method (*(extraArgs + sentArgs))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Airat\Desktop\other-coding\ursina-testin\ursina\samples\venv\Lib\site-packages\ursina\main.py", line 241, in input
    __main__.input(key)
  File "C:\Users\Airat\Desktop\other-coding\ursina-testin\ursina\samples\particle_system.py", line 40, in input
    p = ParticleSystem(position=Vec3(random.random(),random.random(),random.random())*2, color=color.random_color(), rotation_y=random.random()*360)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Airat\Desktop\other-coding\ursina-testin\ursina\samples\particle_system.py", line 17, in __init__
    super().__init__(model=Mesh(vertices=points, mode='point', static=False, render_points_in_3d=True, thickness=.1), t=0, duration=1, **kwargs)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Airat\Desktop\other-coding\ursina-testin\ursina\samples\venv\Lib\site-packages\ursina\mesh.py", line 75, in __init__
    if self.vertices != []:
       ^^^^^^^^^^^^^^^^^^^
ValueError: operands could not be broadcast together with shapes (1000,3) (0,)
```

**Comment by pokepetter** [comment]
`pip uninstall ursina`
`pip install https://github.com/pokepetter/ursina/archive/master.zip`
