### ISSUE TITLE
Exception: Could not open window on Ursina() initialization.

### ISSUE THREAD

**Issue by BezBartek** [pokepetter/ursina#719]
Hello, 
I even can't initialize `Ursina()`

I am getting:
```
info: Using primary monitor: Monitor(x=0, y=0, width=3840, height=2160, width_mm=697, height_mm=392, name='DP-1', is_primary=True)
:prc(warning): Invalid integer value for ConfigVariable win-size: 1728.0
:prc(warning): Invalid integer value for ConfigVariable win-size: 3072.0
Known pipe types:
  glxGraphicsPipe
(4 aux display modules not yet loaded.)
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
:display:glxdisplay(error): Could not find a usable pixel format.
:display:glxdisplay(error): No GLX context: cannot open window.
:display:gsg:glgsg(warning): Unable to query GL_VENDOR
:display:gsg:glgsg(warning): Unable to query GL_RENDERER
:display:gsg:glgsg(warning): Unable to query GL_VERSION
:display:gsg:glgsg(error): Unable to detect OpenGL version
:display:x11display(error): BadValue (integer parameter out of range for operation)
:display:gsg:glgsg(warning): Unable to query GL_VENDOR
:display:gsg:glgsg(warning): Unable to query GL_RENDERER
:display:gsg:glgsg(warning): Unable to query GL_VERSION
:display:gsg:glgsg(error): Unable to detect OpenGL version
:display(warning): Unable to load libtinydisplay.so: No error.
:display(warning): Unable to load libpandadx8.so: No error.
:display(warning): Unable to load libpandadx9.so: No error.
libEGL warning: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)

libEGL warning: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)

libEGL warning: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)

:display:egldisplay(warning): Couldn't initialize the default EGL display: EGL_NOT_INITIALIZED
:ShowBase(warning): Unable to open 'onscreen' window.
Traceback (most recent call last):
  File "/home/bartlomiej/workspace/ursina_engine_test/main.py", line 5, in <module>
    app = Ursina()
          ^^^^^^^^
  File "/home/bartlomiej/miniconda3/envs/ursina_test/lib/python3.11/site-packages/ursina/scripts/singleton_decorator.py", line 4, in getinstance
    cls._instance = cls(**kwargs)
                    ^^^^^^^^^^^^^
  File "/home/bartlomiej/miniconda3/envs/ursina_test/lib/python3.11/site-packages/ursina/main.py", line 65, in __init__
    super().__init__(windowType=application.window_type)
  File "/home/bartlomiej/miniconda3/envs/ursina_test/lib/python3.11/site-packages/direct/showbase/ShowBase.py", line 341, in __init__
    self.openDefaultWindow(startDirect = False, props=props)
  File "/home/bartlomiej/miniconda3/envs/ursina_test/lib/python3.11/site-packages/direct/showbase/ShowBase.py", line 1026, in openDefaultWindow
    self.openMainWindow(*args, **kw)
  File "/home/bartlomiej/miniconda3/envs/ursina_test/lib/python3.11/site-packages/direct/showbase/ShowBase.py", line 1061, in openMainWindow
    self.openWindow(*args, **kw)
  File "/home/bartlomiej/miniconda3/envs/ursina_test/lib/python3.11/site-packages/direct/showbase/ShowBase.py", line 806, in openWindow
    raise Exception('Could not open window.')
Exception: Could not open window.
```

**My distro:**
Linux pop-os x86_64 x86_64 x86_64 GNU/Linux

**Python:** 3.11.9

I have GPU (GA106M [GeForce RTX 3060 Mobile / Max-Q]) and NVIDIA driver for it. 

Thanks for help!

**Comment by pokepetter** [comment]
From my Google search it seems to be an issue with miniconda. Does it work with the default Python?

**Comment by BezBartek** [comment]
@pokepetter 
It works. 
So how to make work it in miniconda environment? Why it does not work there

**Comment by pokepetter** [comment]
No idea.
