### ISSUE TITLE
ZeroDivisionError when changing window size after a window size of zero

### ISSUE THREAD

**Issue by PaologGithub** [pokepetter/ursina#736]
```info: Using primary monitor: Monitor(x=0, y=0, width=1920, height=1200, width_mm=302, height_mm=189, name='\\\\.\\DISPLAY1', is_primary=True)
:prc(warning): Invalid integer value for ConfigVariable win-size: 960.0
:prc(warning): Invalid integer value for ConfigVariable win-size: 1536.0
Known pipe types:
  wglGraphicsPipe
(3 aux display modules not yet loaded.)
set window position: Vec2(192, 120)
:prc(warning): changing default value for ConfigVariable paste-emit-keystrokes from '1' to '0'.
:pnmimage:png(warning): iCCP: known incorrect sRGB profile
package_folder: C:\Users\Paolog\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ursina
asset_folder: .
read obj at: assets\rs\objects\block.obj
:loader(error): Unable to open models_compressed/assets/rs/objects/block.bam
saved .bam to: models_compressed\assets\rs\objects\block.bam
no audio found with name:  supported formats: .ogg, .wav
warning: missing audio clip:
os: Windows
development mode: True
application successfully started
info: changed aspect ratio: 1.6 -> 1.6
info: changed aspect ratio: 1.6 -> 39.385
info: changed aspect ratio: 39.385 -> 1.778
Traceback (most recent call last):
  File "C:\Users\Paolog\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\direct\showbase\EventManager.py", line 49, in eventLoopTask
    self.doEvents()
  File "C:\Users\Paolog\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\direct\showbase\EventManager.py", line 43, in doEvents
    processFunc(dequeueFunc())
  File "C:\Users\Paolog\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\direct\showbase\EventManager.py", line 99, in processEvent
    messenger.send(eventName, paramList)
  File "C:\Users\Paolog\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\direct\showbase\Messenger.py", line 337, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "C:\Users\Paolog\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\direct\showbase\Messenger.py", line 422, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "C:\Users\Paolog\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\direct\showbase\ShowBase.py", line 3004, in windowEvent
    self.adjustWindowAspectRatio(self.getAspectRatio())
  File "C:\Users\Paolog\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\direct\showbase\ShowBase.py", line 3093, in adjustWindowAspectRatio
    messenger.send("aspectRatioChanged")
  File "C:\Users\Paolog\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\direct\showbase\Messenger.py", line 337, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "C:\Users\Paolog\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\direct\showbase\Messenger.py", line 422, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "C:\Users\Paolog\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ursina\window.py", line 230, in update_aspect_ratio
    self.prev_aspect_ratio = self.prev_size[0] / self.prev_size[1]
ZeroDivisionError: float division by zero
:task(error): Exception occurred in PythonTask eventManager
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Paolog\Desktop\Pynecraft\0.1.1\__main__.py", line 64, in <module>
    window.run()
  File "C:\Users\Paolog\Desktop\Pynecraft\0.1.1\src\Graphics\window.py", line 20, in run
    self.app.run()
  File "C:\Users\Paolog\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ursina\main.py", line 321, in run
    super().run()
  File "C:\Users\Paolog\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\direct\showbase\ShowBase.py", line 3331, in run
    self.taskMgr.run()
  File "C:\Users\Paolog\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\direct\task\Task.py", line 553, in run
    self.step()
  File "C:\Users\Paolog\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\direct\task\Task.py", line 504, in step
    self.mgr.poll()
  File "C:\Users\Paolog\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\direct\showbase\EventManager.py", line 49, in eventLoopTask
    self.doEvents()
  File "C:\Users\Paolog\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\direct\showbase\EventManager.py", line 43, in doEvents
    processFunc(dequeueFunc())
  File "C:\Users\Paolog\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\direct\showbase\EventManager.py", line 99, in processEvent
    messenger.send(eventName, paramList)
  File "C:\Users\Paolog\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\direct\showbase\Messenger.py", line 337, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "C:\Users\Paolog\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\direct\showbase\Messenger.py", line 422, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "C:\Users\Paolog\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\direct\showbase\ShowBase.py", line 3004, in windowEvent
    self.adjustWindowAspectRatio(self.getAspectRatio())
  File "C:\Users\Paolog\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\direct\showbase\ShowBase.py", line 3093, in adjustWindowAspectRatio
    messenger.send("aspectRatioChanged")
  File "C:\Users\Paolog\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\direct\showbase\Messenger.py", line 337, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "C:\Users\Paolog\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\direct\showbase\Messenger.py", line 422, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "C:\Users\Paolog\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ursina\window.py", line 230, in update_aspect_ratio
    self.prev_aspect_ratio = self.prev_size[0] / self.prev_size[1]
ZeroDivisionError: float division by zero
```

When you put a window size of 0, and then you resize it, you get a ZeroDivisionError, because of self.prev_size[1] being 0
We can repair this by just putting the function in a TryCatch or by doing a minimum window size

**Comment by pokepetter** [comment]
I think it should crash if you set window size to 0. Needs to be handled.

**Comment by PaologGithub** [comment]
I don't think we need to fix this now, because I saw that on the panda3d GitHub, they are talking about this
