### ISSUE TITLE
AttributeError: module 'builtins' has no attribute 'loader'

### ISSUE THREAD

**Issue by shqln** [pokepetter/ursina#740]
Ursina version 7.0.0
Windows version 10.0.19045 Build 19045

Everything was working last week, one day I started encountering this error when I try to start any ursina script 

> Traceback (most recent call last):
  File "c:\Users\Shiqi\Documents\ursina\what.py", line 1, in <module>
    from ursina import *
  File "C:\Users\Shiqi\miniconda3\envs\ursina\Lib\site-packages\ursina\__init__.py", line 30, in <module>
    from ursina.boxcast import boxcast
  File "C:\Users\Shiqi\miniconda3\envs\ursina\Lib\site-packages\ursina\boxcast.py", line 8, in <module>
    _boxcast_box = Entity(model='cube', origin_z=-.5, collider='box', color=color.white33, enabled=False, eternal=True, add_to_scene_entities=False)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shiqi\miniconda3\envs\ursina\Lib\site-packages\ursina\ursinastuff.py", line 230, in __call__
    obj = type.__call__(cls, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shiqi\miniconda3\envs\ursina\Lib\site-packages\ursina\entity.py", line 107, in __init__
    setattr(self, key, kwargs[key])
  File "C:\Users\Shiqi\miniconda3\envs\ursina\Lib\site-packages\ursina\entity.py", line 198, in model_setter
    m = load_model(value, application.asset_folder)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shiqi\miniconda3\envs\ursina\Lib\site-packages\ursina\mesh_importer.py", line 55, in load_model
    return builtins.loader.loadModel(filename)  # type: ignore
           ^^^^^^^^^^^^^^^
AttributeError: module 'builtins' has no attribute 'loader'

Tried:
- running the basic ursina example scene
- running ursina in python's interactive shell
- reinstalling ursina
- creating fresh venv with different python versions (3.10, 3.11, 3.12)
- creating venv in WSL

all yield the same error message.

**However, installing ursina 6.1.2 and running the basic example scene works fine.** 

Does anyone have an idea why this error occurs in the first place when it used to work perfectly fine? I installed ursina relatively recently so I would have most likely had the same 7.0.0 version.

**Comment by pokepetter** [comment]
I haven't been able to reproduce this. Do you have an MRE?
One thing it could be is that if you have a cube.obj in your project and it tries to load that instead of the included asset, but I couldn't get it to crash even when doing that.
